# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AudioAirlift
email: roy.souryazeppelin14666@gmail.com
description: >-
  AudioAirlift is an AI-powered playlist generator that curates music based on your preferences.
  Easily generate and manage playlists using AI.

baseurl: ""  # Keep empty for the root domain
url: "https://souryajitroy.github.io/audioairlift"

# Set source directory explicitly
source: 

# Remove this line since you're not using Minima anymore:
# theme: minima 

# Set markdown processor
markdown: kramdown
kramdown:
  input: GFM

# Include your layout directory explicitly
include:
  - _layouts
  - assets

# Plugins
plugins:
  - jekyll-feed

# Exclude unnecessary files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/